GET http://localhost:3000/alumnos

###

GET http://localhost:3000/alumnos/2

###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id": "4",
    "nombre": "Valentin",
    "carrera": "BDD"
}

###

PUT http://localhost:3000/alumnos/4
Content-Type: application/json

{
    "id": "5",
    "nombre": "Lucas",
    "carrera": "Sistemas"
}

###

DELETE http://localhost:3000/alumnos/3